version: '3.8'

services:
  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  order-service:
    image: tanjag/order-service-jvm:3.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
      - artemis
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo_db:27017
      - QUARKUS_MONGODB_DATABASE= orderDB
      - QUARKUS_ARTEMIS_URL=tcp://artemis:61616


  artemis:
    image: vromero/activemq-artemis:latest
    ports:
      - "8161:8161"  # Web Console
      - "61616:61616" # AMQP Port
      - "5445:5445"   # Core Port

volumes:
  mongo-data:
